
-- WARNING: TIMESTAMPS are subject to the year 2038 problem. A solution can be proffered as time proceeds.

CREATE TABLE IF NOT EXISTS items(
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(255) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY ( slug ) ,
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS items_quantities(
    
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    item_id INT(11) UNSIGNED NOT NULL,
    quantity INT(11) UNSIGNED NOT NULL,

    expiry DATETIME NOT NULL,

    obsolete BOOLEAN NOT NULL DEFAULT FALSE,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (item_id) REFERENCES items(id),

    INDEX( quantity , expiry , obsolete )
) ENGINE=InnoDB;